CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# REQUIRED because you are using P0.10 (NFC pin)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Boosts the Bluetooth transmission power to max (+8dBm). 
# This dramatically reduces disconnects and lag, with almost zero impact on battery.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enables an experimental ZMK feature that resolves connection issues, 
# especially if you are connecting to Windows machines.
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
